CREATE TABLE posts (
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Post TEXT NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Category VARCHAR(255) NOT NULL,
    Date DATETIME NOT NULL,
    UserID BIGINT NOT NULL,
    Archived TINYINT NOT NULL DEFAULT 0,
    Thumbnail BIGINT,
    FOREIGN KEY (UserID) REFERENCES users(ID)
);
